[
  {
    closed: false,
    desc: "",
    descData: null,
    id: "68072c1cadf5c4e5b4c284f4",
    idEnterprise: null,
    idOrganization: "67eb93a0f82c1b03f65c332b",
    labelNames: {
      black: "",
      black_dark: "",
      black_light: "",
      blue: "",
      blue_dark: "",
      blue_light: "",
      green: "",
      green_dark: "",
      green_light: "",
      lime: "",
      lime_dark: "",
      lime_light: "",
      orange: "",
      orange_dark: "",
      orange_light: "",
      pink: "",
      pink_dark: "",
      pink_light: "",
      purple: "",
      purple_dark: "",
      purple_light: "",
      red: "",
      red_dark: "",
      red_light: "",
      sky: "",
      sky_dark: "",
      sky_light: "",
      yellow: "",
      yellow_dark: "",
      yellow_light: "",
    },
    limits: {},
    name: "00001111",
    pinned: false,
    prefs: {
      background: "blue",
      backgroundBottomColor: "#0079BF",
      backgroundBrightness: "dark",
      backgroundColor: "#0079BF",
      backgroundDarkColor: null,
      backgroundDarkImage: null,
      backgroundImage: null,
      backgroundImageScaled: null,
      backgroundTile: false,
      backgroundTopColor: "#0079BF",
      calendarFeedEnabled: false,
      canBeEnterprise: true,
      canBeOrg: true,
      canBePrivate: true,
      canBePublic: true,
      canInvite: true,
      cardAging: "regular",
      cardCounts: false,
      cardCovers: true,
      comments: "members",
      hiddenPluginBoardButtons: [Array],
      hideVotes: false,
      invitations: "members",
      isTemplate: false,
      permissionLevel: "private",
      selfJoin: true,
      sharedSourceUrl: null,
      showCompleteStatus: true,
      switcherViews: [Array],
      voting: "disabled",
    },
    shortUrl: "https://trello.com/b/Tql7yHDF",
    url: "https://trello.com/b/Tql7yHDF/00001111",
  },
  {
    closed: false,
    creationMethod: "automatic",
    dateClosed: null,
    dateLastActivity: null,
    dateLastView: null,
    datePluginDisable: null,
    desc: "",
    descData: null,
    enterpriseOwned: false,
    id: "67f4c6f6342ab4c747419819",
    idBoardSource: null,
    idEnterprise: null,
    idMemberCreator: "67eb938de8ecaa1f1ae15f79",
    idOrganization: "67eb93a0f82c1b03f65c332b",
    idTags: [],
    ixUpdate: "5",
    labelNames: {
      black: "",
      black_dark: "",
      black_light: "",
      blue: "",
      blue_dark: "",
      blue_light: "",
      green: "",
      green_dark: "",
      green_light: "",
      lime: "",
      lime_dark: "",
      lime_light: "",
      orange: "",
      orange_dark: "",
      orange_light: "",
      pink: "",
      pink_dark: "",
      pink_light: "",
      purple: "",
      purple_dark: "",
      purple_light: "",
      red: "",
      red_dark: "",
      red_light: "",
      sky: "",
      sky_dark: "",
      sky_light: "",
      yellow: "",
      yellow_dark: "",
      yellow_light: "",
    },
    limits: {
      attachments: [Object],
      boards: [Object],
      cards: [Object],
      checkItems: [Object],
      checklists: [Object],
      customFieldOptions: [Object],
      customFields: [Object],
      labels: [Object],
      lists: [Object],
      reactions: [Object],
      stickers: [Object],
    },
    memberships: [[Object]],
    name: "ss",
    nodeId:
      "ari:cloud:trello::board/workspace/67eb93a0f82c1b03f65c332b/67f4c6f6342ab4c747419819",
    pinned: false,
    powerUps: [],
    prefs: {
      background: "blue",
      backgroundBottomColor: "#0079BF",
      backgroundBrightness: "dark",
      backgroundColor: "#0079BF",
      backgroundDarkColor: null,
      backgroundDarkImage: null,
      backgroundImage: null,
      backgroundImageScaled: null,
      backgroundTile: false,
      backgroundTopColor: "#0079BF",
      calendarFeedEnabled: false,
      canBeEnterprise: true,
      canBeOrg: true,
      canBePrivate: true,
      canBePublic: true,
      canInvite: true,
      cardAging: "regular",
      cardCounts: false,
      cardCovers: true,
      comments: "members",
      hiddenPluginBoardButtons: [Array],
      hideVotes: false,
      invitations: "members",
      isTemplate: false,
      permissionLevel: "private",
      selfJoin: true,
      sharedSourceUrl: null,
      showCompleteStatus: true,
      switcherViews: [Array],
      voting: "disabled",
    },
    premiumFeatures: [
      "additionalBoardBackgrounds",
      "additionalStickers",
      "customBoardBackgrounds",
      "customEmoji",
      "customStickers",
      "plugins",
    ],
    shortLink: "prfq6BaV",
    shortUrl: "https://trello.com/b/prfq6BaV",
    starred: false,
    subscribed: false,
    templateGallery: null,
    type: null,
    url: "https://trello.com/b/prfq6BaV/ss",
  },
];
