[
  {
    badges: {
      attachments: 0,
      attachmentsByType: [Object],
      checkItems: 0,
      checkItemsChecked: 0,
      checkItemsEarliestDue: null,
      comments: 0,
      description: false,
      due: null,
      dueComplete: false,
      externalSource: null,
      fogbugz: "",
      lastUpdatedByAi: false,
      location: false,
      maliciousAttachments: 0,
      start: null,
      subscribed: false,
      viewingMemberVoted: false,
      votes: 0,
    },
    cardRole: null,
    checkItemStates: [],
    closed: false,
    cover: {
      brightness: "dark",
      color: null,
      idAttachment: null,
      idPlugin: null,
      idUploadedBackground: null,
      size: "normal",
    },
    dateLastActivity: "2025-04-03T12:58:11.386Z",
    desc: "",
    descData: { emoji: [Object] },
    due: null,
    dueComplete: false,
    dueReminder: null,
    email: null,
    id: "67ee85e3eec83b4545777eac",
    idAttachmentCover: null,
    idBoard: "67ee2da59be4eb3637548dd2",
    idChecklists: [],
    idLabels: [],
    idList: "67ee2da59be4eb3637548e27",
    idMembers: [],
    idMembersVoted: [],
    idShort: 2,
    isTemplate: false,
    labels: [],
    manualCoverAttachment: false,
    mirrorSourceId: null,
    name: "ddd",
    nodeId:
      "ari:cloud:trello::card/workspace/67eb93a0f82c1b03f65c332b/67ee85e3eec83b4545777eac",
    pinned: false,
    pos: 16384,
    shortLink: "JzDKProy",
    shortUrl: "https://trello.com/c/JzDKProy",
    start: null,
    subscribed: false,
    url: "https://trello.com/c/JzDKProy/2-ddd",
  },
];
